# Generated by Django 4.2.13 on 2026-04-27 18:27

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models._upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication_date',
            field=models.CharField(blank=True, help_text='e.g. 2023', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, help_text='Journal / publisher name', max_length=255),
        ),
    ]
